name: Deploy Function Code to Dev

on:
  push:
    tags:
      - dev-*
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Build function code

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build function code
        run: ./build-s3-dist.sh solutions stocktwits-resizing v1.0.4
        working-directory: deployment

      - name: Cache built function code
        uses: actions/upload-artifact@v3
        with:
          name: image-handler.zip
          path: deployment/regional-s3-assets/image-handler.zip

  deploy:
    name: Deploy function code

    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Configure AWS credentials for dev
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::161833574765:role/StocktwitsServerlessImageHandlerGithub
          role-session-name: GithubActions

      - name: Retrieve built function code
        uses: actions/download-artifact@v3
        with:
          name: image-handler.zip

      - name: Deploy function code
        run: aws lambda update-function-code --function-name sih-dev-BackEndImageHandlerLambdaFunctionADEF7FF2-IuMiYd6KWpah --zip-file fileb://`pwd`/image-handler.zip --publish
